name: church_app
description: "RHIC Church Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  shared_preferences: ^2.5.5
  country_flags: ^4.1.2

  just_audio: ^0.10.5
  video_player: ^2.10.0
  dio: ^5.9.0

  path_provider: ^2.1.5

  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/