// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRpFbduKXTeccOzZ6brYYcefELu-OkAoA',
    appId: '1:321066089388:web:168c30c00b057dc6b15809',
    messagingSenderId: '321066089388',
    projectId: 'rhic-ae1ed',
    authDomain: 'rhic-ae1ed.firebaseapp.com',
    storageBucket: 'rhic-ae1ed.firebasestorage.app',
    measurementId: 'G-BTZYTJ19LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU87U2qcWBBFufuI81lhAC67SZ5ilS--w',
    appId: '1:321066089388:android:5f85a928b1b39edeb15809',
    messagingSenderId: '321066089388',
    projectId: 'rhic-ae1ed',
    storageBucket: 'rhic-ae1ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9f5FgBvso3dXb5SqsEPRmgw6X01H4C2M',
    appId: '1:321066089388:ios:17527bf6b9400fddb15809',
    messagingSenderId: '321066089388',
    projectId: 'rhic-ae1ed',
    storageBucket: 'rhic-ae1ed.firebasestorage.app',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9f5FgBvso3dXb5SqsEPRmgw6X01H4C2M',
    appId: '1:321066089388:ios:17527bf6b9400fddb15809',
    messagingSenderId: '321066089388',
    projectId: 'rhic-ae1ed',
    storageBucket: 'rhic-ae1ed.firebasestorage.app',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRpFbduKXTeccOzZ6brYYcefELu-OkAoA',
    appId: '1:321066089388:web:97b7a8d46d2db8a5b15809',
    messagingSenderId: '321066089388',
    projectId: 'rhic-ae1ed',
    authDomain: 'rhic-ae1ed.firebaseapp.com',
    storageBucket: 'rhic-ae1ed.firebasestorage.app',
    measurementId: 'G-R13GEGKSZG',
  );
}
